# Generated by Django 4.0.3 on 2022-09-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_social_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='class1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='class2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
