# Generated by Django 4.0.3 on 2022-09-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_class1_profile_class2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qualify',
        ),
        migrations.AddField(
            model_name='profile',
            name='qualify1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualify2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
