# Generated by Django 4.0.3 on 2022-09-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_qualify_profile_qualify1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skill',
        ),
    ]
