# Generated by Django 4.0.3 on 2022-06-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
